name: "Workflow Telemetry"
description: "Monitor CPU and memory usage during GitHub Actions workflow execution with automatic charts generation"
author: "ke-kawai"

inputs:
  interval:
    description: "Data collection interval in seconds"
    default: "2"
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post.js'

branding:
  icon: "activity"
  color: "blue"
